const ResponseCode = {
    SUCCESS: "SUCCESS",
    FILE_NOT_FOUND: "FILE_NOT_FOUND",
    DATABASE_ERROR: "DATABASE_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
    AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
    MISSING_PARAMETER: "MISSING_PARAMETER",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

const OrderStateCode = {
    PROCESSED: 1,
    CONFIRMED: 2,
    ON_SHIPPED: 3,
    FINISHED: 4,
    CANCELED: 5,
};

module.exports = {
    ResponseCode,
    OrderStateCode,
};
